development:
  adapter: postgresql
  encoding: UTF8
  database: freshlist_development
  username: phillip
  password: password
  host: localhost
test:
  adapter: postgresql
  encoding: UTF8
  database: freshlist_testing<%= ENV['TEST_ENV_NUMBER'] %>
  username: phillip
  password: password
  host: localhost